# Day6 Afternoon

In [5]:
import pandas as pd
print(pd.__version__)

1.5.3


# 1.  NumPy

In [3]:

#popular libraries
"""
1. NumPy
  NumPy is the fundamental package for scientific computing with Python.
  (NumPy is short for "Numerical Python" and used for working with arrays.)
2. Pandas
3. Matplotlib
4. Seaborn

 NumPy providing the underlying array operations and 
 pandas providing high-level data manipulation and analysis capabilities.
"""

#Create a NumPy array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))


#Use a tuple to create a NumPy array:

import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

# Dimensions in Arrays: is one level of array depth (nested arrays).

#0-D Arrays
#0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.
#Create a 0-D array with value 42

import numpy as np

arr = np.array(42)

print(arr)


#1-D Arrays
#1-D arrays, or Scalars are the elements in an array. Each value in an array is  a 1-D array. 

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)


#2-D Arrays
# An array that has 1-D arrays as its elements is called a 2-D array.

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

#3-D Arrays
#An array that has 2-D arrays (matrices) as its elements is called 3-D array.

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr)


# Check how many dimensions the arrays have:

import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

#Access Array Elements
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

#Get third and fourth elements from the following array and add them.
print(arr[2] + arr[3])

#Access 2-D Arrays
#the dimension represents the row and the index represents the column.
# Access the element on the first row, second column:

import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

#Access the element on the 2nd row, 5th column:

import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])


#Access 3-D Arrays
#Access the third element of the second array of the first array:

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

#Negative Indexing
#Print the last element from the 2nd dim:

import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])


#NumPy Array Slicing
#Slice elements from index 1 to index 5 from the following array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

#Slice elements from index 4 to the end of the array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])


#Slice elements from the beginning to index 4 (not included):

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])


#Negative Slicing
#Slice from the index 3 from the end to index 1 from the end:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])


#STEP
#Return every other element from index 1 to index 5:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])


#Slicing 2-D Arrays
#From the second element, slice elements from index 1 to index 4 (not included):

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])



#Checking the Data Type of an Array
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)


#Creating Arrays With a Defined Data Type
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)


#NumPy Array Copy vs View
#The copy SHOULD NOT be affected by the changes made to the original array.
#The view SHOULD be affected by the changes made to the original array.

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

y = arr.view()
y[0] = 31

print(arr)
print(y)

print(x.base) #The copy returns None.
print(y.base) #The view returns the original array.


#Shape of an Array
#The shape of an array is the number of elements in each dimension.

#Print the shape of a 2-D array:

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)





[1 2 3 4 5]
<class 'numpy.ndarray'>
[1 2 3 4 5]
42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
0
1
2
3
1
7
2nd element on 1st row:  2
5th element on 2nd row:  10
6
Last element from 2nd dim:  10
[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[7 8 9]
int32
[b'1' b'2' b'3' b'4']
|S1
[1 2 3 4]
int32
[42  2  3  4  5]
[1 2 3 4 5]
[31  2  3  4  5]
[31  2  3  4  5]
None
[31  2  3  4  5]
(2, 4)


# 2. Pandas

In [2]:
#2. Pandas
#Pandas is a Python library used for working with data sets.
#Pandas allows us to analyze big data and make conclusions based on statistical theories.
#1.Pandas Dataframe
#2. Pandas Series
#3. Read CSV files
#4. Read JSON files


#1. Pandas Series
 #A Pandas Series is like a column in a table.
#It is a one-dimensional array holding data of any type.

import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a)

print(myvar)


#Create your own labels:
#This label can be used to access a specified value.
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a, index = ["x", "y", "z"])

print(myvar)
#Return the value of "y":

print(myvar["y"])


#Create a simple Pandas Series from a dictionary:
#The keys of the dictionary become the labels.
import pandas as pd

calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories)

print(myvar)


#2. DataFrames
#A Pandas DataFrame is a 2 dimensional data structure, like a 2 dimensional array, or a table with rows and columns.
#Series is like a column, a DataFrame is the whole table.


#Create a DataFrame from two Series:

import pandas as pd

import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)

print(df) 

#Locate Row
#Pandas use the loc attribute to return one or more specified row(s)

#refer to the row index:
print(df.loc[0])

#Return row 0 and 1:
#use a list of indexes:
print(df.loc[[0, 1]])

#Named Indexes
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data, index = ["day1", "day2", "day3"])

print(df) 

#refer to the named index:
print(df.loc["day2"])



0    1
1    7
2    2
dtype: int64
x    1
y    7
z    2
dtype: int64
7
day1    420
day2    380
day3    390
dtype: int64
   calories  duration
0       420        50
1       380        40
2       390        45
calories    420
duration     50
Name: 0, dtype: int64
   calories  duration
0       420        50
1       380        40
      calories  duration
day1       420        50
day2       380        40
day3       390        45
calories    380
duration     40
Name: day2, dtype: int64


# 3. Load Files Into a DataFrame

In [ ]:
#3. Load Files Into a DataFrame

#Load a comma separated file (CSV file) into a DataFrame:

import pandas as pd

df = pd.read_csv('data.csv')

print(df) 


#3. Read CSV files
Load the CSV into a DataFrame:

import pandas as pd

df = pd.read_csv('data.csv')

print(df.to_string()) 
#use to_string() to print the entire DataFrame.


#Print the DataFrame without the to_string() method:

import pandas as pd

df = pd.read_csv('data.csv')

print(df) 

#max_rows
#You can check your system's maximum rows with the pd.options.display.max_rows statement.

#Check the number of maximum returned rows:

import pandas as pd

print(pd.options.display.max_rows) 


#Increase the maximum number of rows to display the entire DataFrame:

import pandas as pd

pd.options.display.max_rows = 9999

df = pd.read_csv('data.csv')

print(df) 